food(pizza).
food(noodles).
food(pasta).
bird(parrot).
island(srilanka).
animal(dog).
fruit(kiwi).
weapon(gun).
hardware(keyboard).
android_phone(samsung).
male(kamal).
student(john).
black(elephant).
shape(circle).
vehicle(bus).
